const data = {
  products: [
    {
      _id: '1',
      name: 'First Product',
      slug: '1st-p',
      category: '1st category',
      image: '/images/p1.jpeg', // 679px * 829px
      price: 120,
      countInStock: 10,
      brand: '1st Brand',
      rating: 4.5,
      numReviews: 10,
      description: 'This is the Description for the 1st product',
    },
    {
      _id: '2',
      name: 'Second Product',
      slug: '2nd-p',
      category: '2nd category',
      image: '/images/p2.jpeg',
      price: 100,
      countInStock: 0,
      brand: '2nd Brand',
      rating: 4.0,
      numReviews: 15,
      description: 'This is the Description for the 2nd product',
    },
    {
      _id: '3',
      name: 'Third Product',
      slug: '3rd-p',
      category: '3rd category',
      image: '/images/p3.jpeg',
      price: 80,
      countInStock: 6,
      brand: '3rd Brand',
      rating: 4.5,
      numReviews: 50,
      description: 'This is the Description for the 3rd product',
    },
    {
      _id: '4',
      name: 'Fourth Product',
      slug: '4th-p',
      category: '4th category',
      image: '/images/p4.jpeg',
      price: 50,
      countInStock: 90,
      brand: '4th Brand',
      rating: 5.0,
      numReviews: 30,
      description: 'This is the Description for the 4th product',
    },
  ],
};

export default data;
